#!/usr/bin/env ruby
# coding: utf-8

require 'yaml'
require 'json'
require 'set'
require 'find'

require_relative 'nekosdk2storyconverter'

if ARGV.size != 4
  puts "Usage: bgi2story <meta.yaml> <lang> <in_script> <out_story>"
  exit 1
end

meta_fn, lang, in_script, out_story = ARGV

cnv = Nekosdk2StoryConverter.new(
  in_script,
  YAML.load(File.read(meta_fn)),
#  YAML.load(File.read(chars_fn)),
  lang,
)

cnv.run

File.open(out_story, 'w') { |out|
  out.print "program = "
  out.puts JSON.pretty_generate(cnv.out)
}
